Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Models/Checkout/CheckoutErrorModel.cs
using System;

namespace Contoso.Apps.SportsLeague.Web.Models
{
    /// <summary>
    /// Model holds error information pertaining to the checkout process.
    /// </summary>
    public class CheckoutErrorModel
    {
        public string ErrorCode { get; set; }
        public string LongMessage { get; set; }
        public string ShortMessage { get; set; }

        /// <summary>
        /// Write error Model as a formatted string.
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            string output = string.Format("Error Code: {0}{1}", this.ErrorCode, Environment.NewLine);
            if (!string.IsNullOrWhiteSpace(this.ShortMessage))
            {
                output += string.Format("Message: {0}{1}", this.ShortMessage, Environment.NewLine);
            }
            if (!string.IsNullOrWhiteSpace(this.LongMessage))
            {
                output += string.Format("Detailed Message: {0}", this.LongMessage);
            }
            return output;
        }
    }
}

Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Controllers/CartController.cs
using AutoMapper;
using Contoso.Apps.SportsLeague.Data.Logic;
using Contoso.Apps.SportsLeague.Data.Models;
using Contoso.Apps.SportsLeague.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;

namespace Contoso.Apps.SportsLeague.Web.Controllers
{
    public class CartController : Controller
    {
        public CartController(ProductContext context, IMapper mapper)
        {
            _db = context;
            _mapper = mapper;
        }

        private readonly ProductContext _db;
        private readonly IMapper _mapper;

        // GET: Cart
        public ActionResult Index()
        {
            var cartId = new Helpers.CartHelpers().GetCartId(HttpContext);
            var vm = new CartModel();

            var usersShoppingCart = new ShoppingCartActions(_db, cartId);

            var shoppingCartItems = usersShoppingCart.GetCartItems();
            var cartItemsVM = _mapper.Map<List<CartItemModel>>(shoppingCartItems);
            vm.CartItems = cartItemsVM;
            vm.ItemsTotal = usersShoppingCart.GetCount();
            vm.OrderTotal = usersShoppingCart.GetTotal();
            
            //var shoppingCartItems = db.ShoppingCartItems.Include(c => c.Product);
            return View(vm);
        }

        public async Task<RedirectResult> AddToCart(int productId)
        {
            var cartId = new Helpers.CartHelpers().GetCartId(HttpContext);

            var usersShoppingCart = new ShoppingCartActions(_db, cartId);
            
            await usersShoppingCart.AddToCart(productId);
            
            return Redirect("Index");
        }

        // GET: Cart/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var cartItem = _db.ShoppingCartItems.Find(id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // GET: Cart/Create
        public ActionResult Create()
        {
            ViewBag.ProductId = new SelectList(_db.Products, "ProductID", "ProductName");
            return View();
        }

        // POST: Cart/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("ItemId,CartId,Quantity,DateCreated,ProductId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                _db.ShoppingCartItems.Add(cartItem);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ProductId = new SelectList(_db.Products, "ProductID", "ProductName", cartItem.ProductId);
            return View(cartItem);
        }

        // GET: Cart/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            CartItem cartItem = _db.ShoppingCartItems.Find(id);
            if (cartItem == null)
            {
                return NotFound();
            }
            ViewBag.ProductId = new SelectList(_db.Products, "ProductID", "ProductName", cartItem.ProductId);
            return View(cartItem);
        }

        // POST: Cart/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("ItemId,CartId,Quantity,DateCreated,ProductId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(cartItem).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = new SelectList(_db.Products, "ProductID", "ProductName", cartItem.ProductId);
            return View(cartItem);
        }

        // GET: Cart/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            CartItem cartItem = _db.ShoppingCartItems.Find(id);
            if (cartItem == null)
            {
                return NotFound();
            }
            return View(cartItem);
        }

        // POST: Cart/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            CartItem cartItem = _db.ShoppingCartItems.Find(id);
            _db.ShoppingCartItems.Remove(cartItem);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Controllers/CheckoutController.cs
using AutoMapper;
using Contoso.Apps.Common;
using Contoso.Apps.SportsLeague.Data.Logic;
using Contoso.Apps.SportsLeague.Data.Models;
using Contoso.Apps.SportsLeague.Web.Helpers;
using Contoso.Apps.SportsLeague.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Contoso.Apps.SportsLeague.Web.Controllers
{
    public class CheckoutController : Controller
    {
        public CheckoutController(ProductContext context, IMapper mapper, IConfiguration config)
        {
            _db = context;
            _mapper = mapper;
            _config = config;
        }

        private readonly ProductContext _db;
        private readonly IMapper _mapper;
        private readonly IConfiguration _config;

        private string CartId
        {
            get
            {
                return new Helpers.CartHelpers().GetCartId(HttpContext);
            }
        }

        // GET: Checkout
        public ActionResult Index()
        {
            var vm = new CheckoutModel();
            var usersShoppingCart = new ShoppingCartActions(_db, CartId);
            
            var shoppingCartItems = usersShoppingCart.GetCartItems();
            var cartItemsVM = _mapper.Map<List<CartItemModel>>(shoppingCartItems);
            vm.CartItems = cartItemsVM;
            vm.OrderTotal = usersShoppingCart.GetTotal();
            vm.ItemsTotal = usersShoppingCart.GetCount();
        
            // To make filling out the form faster for demo purposes, pre-fill the values:
            vm.Order = new OrderModel
            {
                // Important! Keep this property here!
                Total = vm.OrderTotal,
                // Prefill properties for convenience:
                FirstName = "Bob",
                LastName = "Loblaw",
                Address = "1313 Mockingbird Lane",
                City = "Virginia Beach",
                State = "VA",
                PostalCode = "23456",
                Country = "United States",
                Email = "bobloblaw@contososportsleague.com",
                Phone = "5551234",
                NameOnCard = "Bob Loblaw",
                CreditCardType = "Visa",
                CreditCardNumber = "4111111111111111",
                ExpirationDate = "12/20",
                CCV = "987",
                SMSOptIn = true
            };

            return View(vm);
        }

        // POST: Checkout/Start
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Review(CheckoutModel data)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var gatewayCaller = new NVPAPICaller(_config, HttpContext);

                    var token = string.Empty;
                    var decoder = new NVPCodec();

                    // Call the gateway payment authorization API:
                    bool ret = gatewayCaller.DoCheckoutAuth(data.Order, ref token, ref decoder);

                    // If authorizaton is successful:
                    if (ret)
                    {
                        // Hydrate a new Order model from our OrderModel.
                        var myOrder = _mapper.Map<Data.Models.Order>(data.Order);
                        // Timestamp with a UTC date.
                        myOrder.OrderDate = DateTime.UtcNow;

                        // Add order to DB.
                        _db.Orders.Add(myOrder);
                        await _db.SaveChangesAsync();

                        // Get the shopping cart items and process them.
                        var usersShoppingCart = new ShoppingCartActions(_db, CartId);
                        
                        List<CartItem> myOrderList = usersShoppingCart.GetCartItems();

                        // Add OrderDetail information to the DB for each product purchased.
                        for (int i = 0; i < myOrderList.Count; i++)
                        {
                            // Create a new OrderDetail object.
                            var myOrderDetail = new OrderDetail();
                            myOrderDetail.OrderId = myOrder.OrderId;
                            myOrderDetail.ProductId = myOrderList[i].ProductId;
                            myOrderDetail.Quantity = myOrderList[i].Quantity;
                            myOrderDetail.UnitPrice = myOrderList[i].Product.UnitPrice;

                            // Add OrderDetail to DB.
                            _db.OrderDetails.Add(myOrderDetail);
                            _db.SaveChanges();
                        }

                        // Set OrderId.
                        HttpContext.Session.SetInt32("currentOrderId", myOrder.OrderId);
                        HttpContext.Session.SetString("Token", token);

                        // Report successful event to Application Insights.
                        var eventProperties = new Dictionary<string, string>();
                        eventProperties.Add("CustomerEmail", data.Order.Email);
                        eventProperties.Add("NumberOfItems", myOrderList.Count.ToString());
                        eventProperties.Add("OrderTotal", data.Order.Total.ToString("C2"));
                        eventProperties.Add("OrderId", myOrder.OrderId.ToString());
                        TelemetryHelper.TrackEvent("SuccessfulPaymentAuth", eventProperties);

                        data.Order.OrderId = myOrder.OrderId;
                        if (data.Order.CreditCardNumber.Length > 4)
                        {
                            // Only show the last 4 digits of the credit card number:
                            data.Order.CreditCardNumber = "xxxxxxxxxxx" + data.Order.CreditCardNumber.Substring(data.Order.CreditCardNumber.Length - 4);
                        }

                    }
                    else
                    {
                        var error = gatewayCaller.PopulateGatewayErrorModel(decoder);

                        // Report failed event to Application Insights.
                        Exception ex = new Exception(error.ToString());
                        ex.Source = "Contoso.Apps.SportsLeague.Web.CheckoutController.cs";
                        TelemetryHelper.TrackException(ex);

                        // Redirect to the checkout error view:
                        return RedirectToAction("Error", error);
                    }
                }
                catch (WebException wex)
                {
                    ExceptionUtility.LogException(wex, "CheckoutController.cs Complete Action");

                    var error = new CheckoutErrorModel
                    {
                        ErrorCode = wex.Message
                    };

                    if (wex.Response != null && wex.Response.GetType() == typeof(HttpWebResponse))
                    {
                        // Extract the response body from the WebException's HttpWebResponse:
                        error.LongMessage = ((HttpWebResponse)wex.Response).StatusDescription;
                    }

                    // Redirect to the checkout error view:
                    return RedirectToAction("Error", error);
                }
                catch (Exception ex)
                {
                    ExceptionUtility.LogException(ex, "CheckoutController.cs Review Action");

                    var error = new CheckoutErrorModel
                    {
                        ErrorCode = ex.Message
                    };

                    // Redirect to the checkout error view:
                    return RedirectToAction("Error", error);
                }
            }

            return View(data);
        }

        // POST: Checkout/Complete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Complete(OrderModel order)
        {
            try
            {
                // TODO: Complete the payment processing via the gateway and update the order...
                var gatewayCaller = new NVPAPICaller(_config, HttpContext);
                var finalPaymentAmount = string.Empty;
                var decoder = new NVPCodec();

                var token = HttpContext.Session.GetString("token");
                //PayerID = Session["payerId"].ToString();
                //finalPaymentAmount = Session["payment_amt"].ToString();
                finalPaymentAmount = order.Total.ToString("C2");

                var ret = gatewayCaller.DoCheckoutPayment(finalPaymentAmount, token, ref decoder);
                if (ret)
                {
                    // Retrieve PayPal confirmation value.
                    string PaymentConfirmation = decoder[NVPProperties.Properties.TRANSACTIONID].ToString();
                    order.PaymentTransactionId = PaymentConfirmation;

                    // Get the current order id.
                    int currentOrderId = -1;
                    if (HttpContext.Session.GetInt32("currentOrderId") != null && HttpContext.Session.GetInt32("currentOrderId")?.ToString() != string.Empty)
                    {
                        currentOrderId = Convert.ToInt32(HttpContext.Session.GetInt32("currentOrderId"));
                    }
                    Order myCurrentOrder;
                    if (currentOrderId >= 0)
                    {
                        // Get the order based on order id.
                        myCurrentOrder = _db.Orders.Single(o => o.OrderId == currentOrderId);
                        // Update the order to reflect payment has been completed.
                        myCurrentOrder.PaymentTransactionId = PaymentConfirmation;
                        // Save to DB.
                        await _db.SaveChangesAsync();

Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Views/Checkout/Complete.cshtml
@model Contoso.Apps.SportsLeague.Web.Models.OrderModel

@{
    ViewBag.Title = "Index";
}

@section HeaderOverlay {
    <div class="button-wrapper">
        <div class="container">
            <div class="row">
                <a href="#" class="btn-content">Order Completed</a>
            </div>
        </div>
    </div>
}

<section class="store">
    <div class="container">
        <div class="row">
            <div class="wrapper clearfix">

                @if (!string.IsNullOrWhiteSpace(Model.PaymentTransactionId))
                {
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h3 class="panel-title">Success!</h3>
                        </div>
                        <div class="panel-body">
                            <p>Thank you for your business! Your order has been completed. Here's your transaction Id for reference: <strong>@Model.PaymentTransactionId</strong></p>
                            <p><br /></p>
                            <p><a href="@Url.Action("Index", "Home")" class="btn red-btn">Return Home</a></p>
                        </div>
                    </div>
                }
                else
                {
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title">Payment has not been completed</h3>
                        </div>
                        <div class="panel-body">
                            <p>Oh no! I must've mistakenly brought you to this page. You have not completed your order yet...</p>
                            <p>Let's <a href="@Url.Action("Index", "Cart")" style="color: blue">take a look at your cart</a> and try again!</p>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</section>

Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Views/Checkout/Index.cshtml
@model Contoso.Apps.SportsLeague.Web.Models.CheckoutModel

@{
    ViewBag.Title = "Index";
}

@section HeaderOverlay {
    <div class="button-wrapper">
        <div class="container">
            <div class="row">
                <a href="#" class="btn-content">Order Checkout</a>
            </div>
        </div>
    </div>
}

<section class="store">
    <div class="container">
        <div class="row">
            <div class="wrapper clearfix">

                @if (Model.ItemsTotal > 0)
                {
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">Order Summary</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-2"><strong>Total Items:</strong></div>
                                <div class="col-md-10">@Model.ItemsTotal</div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><strong>Order Total:</strong></div>
                                <div class="col-md-10">@String.Format("{0:c}", Model.OrderTotal)</div>
                            </div>
                        </div>
                    </div>

                    using (Html.BeginForm("Review", "Checkout"))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.Order.Total)
                        @Html.HiddenFor(model => model.ItemsTotal)
                        @Html.HiddenFor(model => model.OrderTotal)

                        <div class="form-horizontal">
                            <h4>Contact Information</h4>
                            <hr />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.FirstName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.LastName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.Address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.Address, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.City, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.City, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.City, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.State, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.State, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.State, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.PostalCode, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.Country, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.Country, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.Phone, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.Phone, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.SMSOptIn, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.SMSOptIn)
                                </div>
                            </div>

                        </div>

                        <div class="form-horizontal">
                            <h4>Payment Information</h4>
                            <hr />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.NameOnCard, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.NameOnCard, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.NameOnCard, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.CreditCardType, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.Order.CreditCardType, Model.CreditCardTypes, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.CreditCardType, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.CreditCardNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.CreditCardNumber, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.CreditCardNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.ExpirationDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Order.CCV, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Order.CCV, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Order.CCV, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>

                        <div class="pull-right">
                            <input type="submit" class="btn btn-primary" value="Continue" />
                        </div>

                        <div class="pull-left">
                            <a href="@Url.Action("Index", "Cart")" class="btn trans-btn"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;Cancel</a>
                        </div>
                    }

                }
                else
                {
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title">Your shopping cart is empty</h3>
                        </div>
                        <div class="panel-body">
                            <p>Oops! You haven't added anything to your shopping cart yet!</p>
                            <p>You may have forgotten to add something to the cart. How about <a href="@Url.Action("Index", "Store")" style="color: blue">you take another look</a> at our selection of awesome products to try again?</p>
                        </div>
                    </div>
                }

                @section Scripts {
                    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
                }
            </div>
        </div>
    </div>
</section>