Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Models/Cart/CartItemModel.cs
namespace Contoso.Apps.SportsLeague.Web.Models
{
    public class CartItemModel
    {
        public string ItemId { get; set; }

        public string CartId { get; set; }

        public int Quantity { get; set; }

        public System.DateTime DateCreated { get; set; }

        public int ProductId { get; set; }

        public string ProductProductName { get; set; }

        public string ProductThumbnailPath { get; set; }

        public double? ProductUnitPrice { get; set; }
    }
}

Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Controllers/CheckoutController.cs
using AutoMapper;
using Contoso.Apps.Common;
using Contoso.Apps.SportsLeague.Data.Logic;
using Contoso.Apps.SportsLeague.Data.Models;
using Contoso.Apps.SportsLeague.Web.Helpers;
using Contoso.Apps.SportsLeague.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Contoso.Apps.SportsLeague.Web.Controllers
{
    public class CheckoutController : Controller
    {
        public CheckoutController(ProductContext context, IMapper mapper, IConfiguration config)
        {
            _db = context;
            _mapper = mapper;
            _config = config;
        }

        private readonly ProductContext _db;
        private readonly IMapper _mapper;
        private readonly IConfiguration _config;

        private string CartId
        {
            get
            {
                return new Helpers.CartHelpers().GetCartId(HttpContext);
            }
        }

        // GET: Checkout
        public ActionResult Index()
        {
            var vm = new CheckoutModel();
            var usersShoppingCart = new ShoppingCartActions(_db, CartId);
            
            var shoppingCartItems = usersShoppingCart.GetCartItems();
            var cartItemsVM = _mapper.Map<List<CartItemModel>>(shoppingCartItems);
            vm.CartItems = cartItemsVM;
            vm.OrderTotal = usersShoppingCart.GetTotal();
            vm.ItemsTotal = usersShoppingCart.GetCount();
        
            // To make filling out the form faster for demo purposes, pre-fill the values:
            vm.Order = new OrderModel
            {
                // Important! Keep this property here!
                Total = vm.OrderTotal,
                // Prefill properties for convenience:
                FirstName = "Bob",
                LastName = "Loblaw",
                Address = "1313 Mockingbird Lane",
                City = "Virginia Beach",
                State = "VA",
                PostalCode = "23456",
                Country = "United States",
                Email = "bobloblaw@contososportsleague.com",
                Phone = "5551234",
                NameOnCard = "Bob Loblaw",
                CreditCardType = "Visa",
                CreditCardNumber = "4111111111111111",
                ExpirationDate = "12/20",
                CCV = "987",
                SMSOptIn = true
            };

            return View(vm);
        }

        // POST: Checkout/Start
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Review(CheckoutModel data)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var gatewayCaller = new NVPAPICaller(_config, HttpContext);

                    var token = string.Empty;
                    var decoder = new NVPCodec();

                    // Call the gateway payment authorization API:
                    bool ret = gatewayCaller.DoCheckoutAuth(data.Order, ref token, ref decoder);

                    // If authorizaton is successful:
                    if (ret)
                    {
                        // Hydrate a new Order model from our OrderModel.
                        var myOrder = _mapper.Map<Data.Models.Order>(data.Order);
                        // Timestamp with a UTC date.
                        myOrder.OrderDate = DateTime.UtcNow;

                        // Add order to DB.
                        _db.Orders.Add(myOrder);
                        await _db.SaveChangesAsync();

                        // Get the shopping cart items and process them.
                        var usersShoppingCart = new ShoppingCartActions(_db, CartId);
                        
                        List<CartItem> myOrderList = usersShoppingCart.GetCartItems();

                        // Add OrderDetail information to the DB for each product purchased.
                        for (int i = 0; i < myOrderList.Count; i++)
                        {
                            // Create a new OrderDetail object.
                            var myOrderDetail = new OrderDetail();
                            myOrderDetail.OrderId = myOrder.OrderId;
                            myOrderDetail.ProductId = myOrderList[i].ProductId;
                            myOrderDetail.Quantity = myOrderList[i].Quantity;
                            myOrderDetail.UnitPrice = myOrderList[i].Product.UnitPrice;

                            // Add OrderDetail to DB.
                            _db.OrderDetails.Add(myOrderDetail);
                            _db.SaveChanges();
                        }

                        // Set OrderId.
                        HttpContext.Session.SetInt32("currentOrderId", myOrder.OrderId);
                        HttpContext.Session.SetString("Token", token);

                        // Report successful event to Application Insights.
                        var eventProperties = new Dictionary<string, string>();
                        eventProperties.Add("CustomerEmail", data.Order.Email);
                        eventProperties.Add("NumberOfItems", myOrderList.Count.ToString());
                        eventProperties.Add("OrderTotal", data.Order.Total.ToString("C2"));
                        eventProperties.Add("OrderId", myOrder.OrderId.ToString());
                        TelemetryHelper.TrackEvent("SuccessfulPaymentAuth", eventProperties);

                        data.Order.OrderId = myOrder.OrderId;
                        if (data.Order.CreditCardNumber.Length > 4)
                        {
                            // Only show the last 4 digits of the credit card number:
                            data.Order.CreditCardNumber = "xxxxxxxxxxx" + data.Order.CreditCardNumber.Substring(data.Order.CreditCardNumber.Length - 4);
                        }

                    }
                    else
                    {
                        var error = gatewayCaller.PopulateGatewayErrorModel(decoder);

                        // Report failed event to Application Insights.
                        Exception ex = new Exception(error.ToString());
                        ex.Source = "Contoso.Apps.SportsLeague.Web.CheckoutController.cs";
                        TelemetryHelper.TrackException(ex);

                        // Redirect to the checkout error view:
                        return RedirectToAction("Error", error);
                    }
                }
                catch (WebException wex)
                {
                    ExceptionUtility.LogException(wex, "CheckoutController.cs Complete Action");

                    var error = new CheckoutErrorModel
                    {
                        ErrorCode = wex.Message
                    };

                    if (wex.Response != null && wex.Response.GetType() == typeof(HttpWebResponse))
                    {
                        // Extract the response body from the WebException's HttpWebResponse:
                        error.LongMessage = ((HttpWebResponse)wex.Response).StatusDescription;
                    }

                    // Redirect to the checkout error view:
                    return RedirectToAction("Error", error);
                }
                catch (Exception ex)
                {
                    ExceptionUtility.LogException(ex, "CheckoutController.cs Review Action");

                    var error = new CheckoutErrorModel
                    {
                        ErrorCode = ex.Message
                    };

                    // Redirect to the checkout error view:
                    return RedirectToAction("Error", error);
                }
            }

            return View(data);
        }

        // POST: Checkout/Complete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Complete(OrderModel order)
        {
            try
            {
                // TODO: Complete the payment processing via the gateway and update the order...
                var gatewayCaller = new NVPAPICaller(_config, HttpContext);
                var finalPaymentAmount = string.Empty;
                var decoder = new NVPCodec();

                var token = HttpContext.Session.GetString("token");
                //PayerID = Session["payerId"].ToString();
                //finalPaymentAmount = Session["payment_amt"].ToString();
                finalPaymentAmount = order.Total.ToString("C2");

                var ret = gatewayCaller.DoCheckoutPayment(finalPaymentAmount, token, ref decoder);
                if (ret)
                {
                    // Retrieve PayPal confirmation value.
                    string PaymentConfirmation = decoder[NVPProperties.Properties.TRANSACTIONID].ToString();
                    order.PaymentTransactionId = PaymentConfirmation;

                    // Get the current order id.
                    int currentOrderId = -1;
                    if (HttpContext.Session.GetInt32("currentOrderId") != null && HttpContext.Session.GetInt32("currentOrderId")?.ToString() != string.Empty)
                    {
                        currentOrderId = Convert.ToInt32(HttpContext.Session.GetInt32("currentOrderId"));
                    }
                    Order myCurrentOrder;
                    if (currentOrderId >= 0)
                    {
                        // Get the order based on order id.
                        myCurrentOrder = _db.Orders.Single(o => o.OrderId == currentOrderId);
                        // Update the order to reflect payment has been completed.
                        myCurrentOrder.PaymentTransactionId = PaymentConfirmation;
                        // Save to DB.
                        await _db.SaveChangesAsync();

Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Controllers/StoreController.cs
using AutoMapper;
using Contoso.Apps.Common.Extensions;
using Contoso.Apps.SportsLeague.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;

namespace Contoso.Apps.SportsLeague.Web.Controllers
{
    public class StoreController : Controller
    {
        public StoreController(ProductContext context, IMapper mapper)
        {
            _db = context;
            _mapper = mapper;
        }

        private readonly ProductContext _db;
        private readonly IMapper _mapper;

        // GET: Store
        public ActionResult Index()
        {
            var products = _db.Products; //.Include(p => p.Category);
            var productsVm = _mapper.Map<List<Models.ProductListModel>>(products);

            // Retrieve category listing:
            var categories = _db.Categories.ToList();
            var categoriesVm = _mapper.Map<List<Models.CategoryModel>>(categories);

            var vm = new Models.StoreIndexModel
            {
                Products = productsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        // GET: Store/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Product product = _db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }
            var productVm = _mapper.Map<Models.ProductModel>(product);

            // Find related products, based on the category:
            var relatedProducts = _db.Products.Where(p => p.CategoryID == product.CategoryID && p.ProductID != product.ProductID).ToList();
            var relatedProductsVm = _mapper.Map<List<Models.ProductListModel>>(relatedProducts);

            // Retrieve category listing:
            var categories = _db.Categories.ToList();
            var categoriesVm = _mapper.Map<List<Models.CategoryModel>>(categories);

            // Retrieve "new products" as a list of three random products not equal to the displayed one:
            var newProducts = _db.Products.Where(p => p.ProductID != product.ProductID).ToList().Shuffle().Take(3);

            var newProductsVm = _mapper.Map<List<Models.ProductListModel>>(newProducts);

            var vm = new Models.StoreDetailsModel
            {
                Product = productVm,
                RelatedProducts = relatedProductsVm,
                NewProducts = newProductsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hands-on lab/lab-files/src/Contoso Sports League/Contoso.Apps.SportsLeague.Web/Views/Cart/Index.cshtml
@model Contoso.Apps.SportsLeague.Web.Models.CartModel

@{
    ViewBag.Title = "Index";
}

@section HeaderOverlay {
    <div class="button-wrapper">
        <div class="container">
            <div class="row">
                <a href="#" class="btn-content">Shopping Cart</a>
            </div>
        </div>
    </div>
}

<section class="store">
    <div class="container">
        <div class="row">
            <div class="wrapper clearfix">

                @if (Model.CartItems.Count > 0)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>
                                    Product Name
                                </th>
                                <th>
                                    Price
                                </th>
                                <th>
                                    Quantity
                                </th>
                                <th>
                                    Total
                                </th>
                                @*<th></th>*@
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.CartItems)
                            {
                                <tr>
                                    <td>
                                        <img src="@Url.Content("~/images/Products/")@item.ProductThumbnailPath" alt="@item.ProductProductName" class="center-block">
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Details", "Store", new { id = item.ProductId })">@Html.DisplayFor(modelItem => item.ProductProductName)</a>
                                    </td>
                                    <td>
                                        @String.Format("{0:c}", item.ProductUnitPrice)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td>
                                        @String.Format("{0:c}", (item.ProductUnitPrice.HasValue ? Math.Round(item.ProductUnitPrice.Value * item.Quantity, 2) : 0))
                                    </td>
                                    @*<td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.ItemId }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.ItemId }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.ItemId })
                                        </td>*@
                                </tr>
                            }
                        </tbody>
                    </table>

                    <hr />

                    <div class="row">
                        <div class="col-xs-6 col-sm-8 col-md-10 col-lg-11 text-right text-warning"><strong># of Items:</strong></div>
                        <div class="col-xs-6 col-sm-4 col-md-2 col-lg-1 text-warning">@Model.ItemsTotal</div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-8 col-md-10 col-lg-11 text-right text-warning"><strong>Total:</strong></div>
                        <div class="col-xs-6 col-sm-4 col-md-2 col-lg-1 text-warning">@String.Format("{0:c}", Model.OrderTotal)</div>
                    </div>
                    
                    <div class="row">
                        <div class="col-sm-12">
                            &nbsp;
                        </div>
                    </div>

                    <div class="pull-right">
                        <a href="@Url.Action("Index", "Checkout")" class="btn btn-primary">Checkout</a>
                    </div>

                    <div class="pull-left">
                        <a href="@Url.Action("Index", "Store")" class="btn trans-btn"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;Keep shopping</a>
                    </div>
                }
                else
                {
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title">Your shopping cart is empty</h3>
                        </div>
                        <div class="panel-body">
                            <p>Oops! You haven't added anything to your shopping cart yet!</p>
                            <p>You may have forgotten to add something to the cart. How about <a href="@Url.Action("Index", "Store")" style="color: blue">you take another look</a> at our selection of awesome products to try again?</p>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</section>